### ISSUE TITLE
No Details on use

### ISSUE THREAD

**Issue by jarrard** [40163650/FSRForReShade#1]
You've said this works with OLD reshade for dx11, but haven't given details on howto use it.  What entries need to be edited into the .fx files for example etc...

Also should this work with DX12 if the newer DX12 reshade dll is used? 

I ask because I'm having major issues with the Magpie FSR app where it causes fps smoothing to go to trash and make everything nano/micro-skip allot, also it does not work with VRR, hence I'm looking for a more automatic and seamless solution much like how its done under Linux with Wine-FSR.

**Comment by 40163650** [comment]
Thanks for letting me know.

I've updated the readme with instructions on how to get it set up.

It should theoretically work with the DirectX12 version.

This won't improve your FPS if that's what you're trying to do, but it shouldn't cause any stuttering / skipping. It's essentially an anti-aliasing technique. Internally, your game will still run at its native resolution.

**Comment by jarrard** [comment]
> This won't improve your FPS if that's what you're trying to do,

The whole point of FSR is it improves fps by upscaling, so if I set 1800p it should upscale it to 2160p my native resolution?

Also what about FSR sharpening strength? can that be adjusted.  The info you added suggests your shader is not automatic in detecting native resolution?

The issue with magpie app was it did increase fps allot but also introduced this frame skipping when I panned the camera around which made it felt like lower fps which was bad. I mean it felt worse at 120fps then it did at 50fps due to this frame pacing/skipping issue.

**Comment by jarrard** [comment]
So I set: rendersize = float2(2560, 1440);  which will upscale to 2160p when app is in fullscreen and set to 1440p resolution?  This should give me fps of 1440p?  Or should I define target resolution of 2160p somewhere?


Also have you considered updating to latest fx/fxh method in reshade4?

**Comment by 40163650** [comment]
To my knowledge, it is beyond the capabilities of reshade to change the internal resolution of the game. It is purely a post-processing effect.

The target resolution is defined by BUFFER_WIDTH and BUFFER_HEIGHT. These values are the size of the game window. You can change them on line 260 of the shader if you want.

Think of it like this, you have 3 resolutions, they are applied in this order:

Native resolution (what you set in the game) -> rendersize (this is scaled to linearly) -> Target Resolution (scaled to using FSR, the same as native resolution by default)

If you set rendersize to a value higher than the one used on the next line, you will get something like this:
![image](https://user-images.githubusercontent.com/12065481/147008688-47deb428-6212-4702-96d6-4d2458173c78.png)

**Comment by 40163650** [comment]
If you set the resolution of the game to say 1920x1080, and rendersize to 1920x1080 and the target resolution to 3840x2160, you get something like this:
![image](https://user-images.githubusercontent.com/12065481/147009615-fb45d5fc-63e8-457e-b894-5711bc1da0fe.png)

And for me, making that fullscreen doesn't extend what you can see.

**Comment by jarrard** [comment]
whats the point of using fsr to get the input and output resolution the same? isn't that wholly wasteful?

**Comment by 40163650** [comment]
Like I said, it's useful for antialiasing.
